package bunsession

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/emergent-company/emergent.memory/internal/testdb"
)

// TestADKStateRoundTripsRealSchema is the database-backed regression test for
// #1093: the ADKState model had drifted from kb.adk_states (missing the id PK
// and treating user_id as a phantom primary key). It proves the model now
// round-trips a row against the real migrated schema: the id PK is generated by
// the database default and user_id/session_id are nullable (NULL for app scope).
func TestADKStateRoundTripsRealSchema(t *testing.T) {
	if testing.Short() {
		testdb.SkipOrFatal(t, "skipping database-backed test in short mode")
	}
	ctx := context.Background()
	tdb := testdb.SetupTestDBOrFail(t, ctx, "adk_state_roundtrip")
	defer tdb.Close()

	db := tdb.DB

	// App-scope state: user_id/session_id are empty, so they must be persisted
	// as NULL (the columns are nullable) and the id PK must be generated.
	appState := &ADKState{
		Scope:   "app",
		AppName: "agents",
		State:   map[string]interface{}{"greeting": "hello"},
	}
	_, err := db.NewInsert().Model(appState).Exec(ctx)
	require.NoError(t, err, "insert app-scope ADKState against real schema")

	require.NotEmpty(t, appState.ID, "id PK must be generated by the database default")
	require.NotNil(t, appState.State)

	// Read it back and confirm the row round-trips with a non-null id and
	// NULL-mapped empty user_id/session_id.
	var got ADKState
	err = db.NewSelect().Model(&got).
		Where("scope = ? AND app_name = ?", "app", "agents").
		Scan(ctx)
	require.NoError(t, err, "select app-scope ADKState back")
	require.Equal(t, appState.ID, got.ID, "id PK must round-trip")
	require.Equal(t, "app", got.Scope)
	require.Equal(t, "agents", got.AppName)
	require.Equal(t, "", got.UserID, "NULL user_id scans as empty string")
	require.Equal(t, "", got.SessionID, "NULL session_id scans as empty string")
	require.Equal(t, "hello", got.State["greeting"])

	// User-scope state: user_id set, session_id empty (NULL).
	userState := &ADKState{
		Scope:   "user",
		AppName: "agents",
		UserID:  "user-123",
		State:   map[string]interface{}{"pref": "dark"},
	}
	_, err = db.NewInsert().Model(userState).Exec(ctx)
	require.NoError(t, err, "insert user-scope ADKState against real schema")

	var gotUser ADKState
	err = db.NewSelect().Model(&gotUser).
		Where("scope = ? AND app_name = ? AND user_id = ?", "user", "agents", "user-123").
		Scan(ctx)
	require.NoError(t, err, "select user-scope ADKState back")
	require.Equal(t, userState.ID, gotUser.ID)
	require.Equal(t, "user-123", gotUser.UserID)
	require.Equal(t, "", gotUser.SessionID)
	require.Equal(t, "dark", gotUser.State["pref"])
}
