console.log('Test script start');
console.log('UV_THREADPOOL_SIZE:', process.env.UV_THREADPOOL_SIZE);
console.log('Loading reflect-metadata...');
require('reflect-metadata');
console.log('reflect-metadata loaded');
console.log('Loading @nestjs/common...');
require('@nestjs/common');
console.log('@nestjs/common loaded');
console.log('Loading @nestjs/core...');
require('@nestjs/core');
console.log('@nestjs/core loaded');
