package sandbox

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"io"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
)

// storeCaptureDriver records SQL generated by the Store so query-shape tests
// can assert on the guards that protect live runs and in-flight servers without
// a live database. It returns an empty result set for SELECTs.
type storeCaptureDriver struct {
	mu      sync.Mutex
	queries []string
}

func (d *storeCaptureDriver) record(query string) {
	d.mu.Lock()
	d.queries = append(d.queries, query)
	d.mu.Unlock()
}

func (d *storeCaptureDriver) reset() {
	d.mu.Lock()
	d.queries = nil
	d.mu.Unlock()
}

func (d *storeCaptureDriver) last() string {
	d.mu.Lock()
	defer d.mu.Unlock()
	if len(d.queries) == 0 {
		return ""
	}
	return d.queries[len(d.queries)-1]
}

func (d *storeCaptureDriver) Open(string) (driver.Conn, error) {
	return &storeCaptureConn{d: d}, nil
}

type storeCaptureConn struct{ d *storeCaptureDriver }

func (c *storeCaptureConn) Prepare(string) (driver.Stmt, error) {
	return nil, errors.New("not implemented")
}
func (c *storeCaptureConn) Close() error              { return nil }
func (c *storeCaptureConn) Begin() (driver.Tx, error) { return storeCaptureTx{}, nil }
func (c *storeCaptureConn) ExecContext(_ context.Context, query string, _ []driver.NamedValue) (driver.Result, error) {
	c.d.record(query)
	return driver.RowsAffected(0), nil
}
func (c *storeCaptureConn) QueryContext(_ context.Context, query string, _ []driver.NamedValue) (driver.Rows, error) {
	c.d.record(query)
	return storeCaptureRows{}, nil
}

type storeCaptureTx struct{}

func (storeCaptureTx) Commit() error   { return nil }
func (storeCaptureTx) Rollback() error { return nil }

type storeCaptureRows struct{}

func (storeCaptureRows) Columns() []string         { return nil }
func (storeCaptureRows) Close() error              { return nil }
func (storeCaptureRows) Next([]driver.Value) error { return io.EOF }

var (
	storeCaptureOnce   sync.Once
	storeCaptureGlobal = &storeCaptureDriver{}
)

func newCaptureStore(t *testing.T) (*Store, *storeCaptureDriver) {
	t.Helper()
	storeCaptureOnce.Do(func() { sql.Register("sandbox_store_capture", storeCaptureGlobal) })
	storeCaptureGlobal.reset()
	sqldb, err := sql.Open("sandbox_store_capture", "")
	require.NoError(t, err)
	t.Cleanup(func() { _ = sqldb.Close() })
	return NewStore(bun.NewDB(sqldb, pgdialect.New())), storeCaptureGlobal
}

func TestStore_ListIdlePersistentMCPServers_QueryGuards(t *testing.T) {
	store, drv := newCaptureStore(t)

	_, err := store.ListIdlePersistentMCPServers(context.Background(), time.Now().AddDate(0, 0, -7))
	require.NoError(t, err)

	q := drv.last()
	require.NotEmpty(t, q)
	assert.Contains(t, q, "mcp_server", "must filter to MCP servers")
	assert.Contains(t, q, "persistent", "must filter to the persistent lifecycle")
	assert.Contains(t, q, "creating")
	assert.Contains(t, q, "stopping")
	assert.Contains(t, q, "COALESCE(last_used_at, created_at)", "idle age uses last_used_at falling back to creation time")
	assert.Contains(t, q, "agent_sandboxes", "must read the sandbox table")
}

func TestStore_ListOrphanedSandboxes_QueryGuards(t *testing.T) {
	store, drv := newCaptureStore(t)

	_, err := store.ListOrphanedSandboxes(context.Background(), []string{"submitted", "working", "cancelling"})
	require.NoError(t, err)

	q := drv.last()
	require.NotEmpty(t, q)
	assert.Contains(t, q, "agent_sandbox", "must filter to agent sandboxes")
	assert.Contains(t, q, "agent_session_id IS NOT NULL", "rows with no linked run are not assumed orphaned")
	assert.Contains(t, q, "kb.agent_runs", "orphan status is derived from the owning run")
	assert.Contains(t, q, "submitted")
	assert.Contains(t, q, "working")
	assert.Contains(t, q, "cancelling")
	assert.Contains(t, q, "stopped")
	assert.Contains(t, q, "error")
	assert.True(t, strings.Contains(q, "NOT IN"), "must exclude live/terminal states")
}
