package routeguard

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// tableVersion is the current on-disk format version.
const tableVersion = 1

// tableHeader is prepended to the generated YAML. It must stay stable so that
// --update regenerating an unchanged tree produces a byte-identical file.
const tableHeader = `# Route -> authority conformance table.
#
# Generated by: go run ./cmd/route-authority-guard -update
# Do not hand-edit the level column. The authority tier of a route is derived
# from the middleware chain applied in apps/server/domain/*/{routes,module}.go;
# change the middleware in code, then regenerate, so the diff is the review
# surface.
#
# Levels (strongest wins):
#   public           no RequireAuth / a2aStreamingAuthMiddleware in the chain
#   auth             RequireAuth (or a2aStreamingAuthMiddleware), no project gate
#   project-token    RequireProjectTokenScope, no RequireProjectMember
#   project-member   RequireProjectMember (with or without token scope)
#   superadmin-full  RequireSuperadminFull
#
# The 'note' column records the full derived middleware chain for reviewer
# context and is informational (a note-only drift warns but does not fail).
#
# Scope of the scan: apps/server/domain only. Handler-level authorization (e.g.
# backups requireOrgAdmin, skills requireProjectMember) is NOT part of the
# middleware tier and is tracked separately (#1041).
`

// Table is the on-disk route→authority expectations file.
type Table struct {
	Version int     `yaml:"version"`
	Routes  []Route `yaml:"routes"`
}

// Violation is a single conformance failure.
type Violation struct {
	Kind     string // "undeclared", "vanished", "level-mismatch"
	Method   string
	Path     string
	Derived  Level
	Declared Level
}

// LoadTable reads and validates the declared table from disk.
func LoadTable(path string) (*Table, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var t Table
	if err := yaml.Unmarshal(data, &t); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if t.Version != tableVersion {
		return nil, fmt.Errorf("unsupported table version %d (want %d)", t.Version, tableVersion)
	}
	seen := map[string]bool{}
	for i, r := range t.Routes {
		if !ValidLevels[r.Level] {
			return nil, fmt.Errorf("%s: route %d (%s %s) has invalid level %q", path, i, r.Method, r.Path, r.Level)
		}
		key := r.Method + " " + r.Path
		if seen[key] {
			return nil, fmt.Errorf("%s: duplicate route entry %s %s", path, r.Method, r.Path)
		}
		seen[key] = true
	}
	sortRoutes(t.Routes)
	return &t, nil
}

// SaveTable writes the table to disk, prepending the stable header.
func SaveTable(path string, t *Table) error {
	sortRoutes(t.Routes)
	t.Version = tableVersion
	body, err := yaml.Marshal(t)
	if err != nil {
		return fmt.Errorf("marshal table: %w", err)
	}
	out := tableHeader + "\n" + string(body)
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// Compare returns the conformance violations between the derived route set and
// the declared table, plus note-only drifts (warnings, not failures).
func Compare(derived []Route, declared *Table) (violations []Violation, noteDrifts []Route) {
	declaredByKey := make(map[string]Route, len(declared.Routes))
	for _, r := range declared.Routes {
		declaredByKey[r.Method+" "+r.Path] = r
	}

	seenDerived := make(map[string]bool, len(derived))
	for _, d := range derived {
		key := d.Method + " " + d.Path
		seenDerived[key] = true
		dec, ok := declaredByKey[key]
		if !ok {
			violations = append(violations, Violation{
				Kind:    "undeclared",
				Method:  d.Method,
				Path:    d.Path,
				Derived: d.Level,
			})
			continue
		}
		if dec.Level != d.Level {
			violations = append(violations, Violation{
				Kind:     "level-mismatch",
				Method:   d.Method,
				Path:     d.Path,
				Derived:  d.Level,
				Declared: dec.Level,
			})
		} else if dec.Note != d.Note {
			noteDrifts = append(noteDrifts, d)
		}
	}

	for _, r := range declared.Routes {
		key := r.Method + " " + r.Path
		if !seenDerived[key] {
			violations = append(violations, Violation{
				Kind:     "vanished",
				Method:   r.Method,
				Path:     r.Path,
				Declared: r.Level,
			})
		}
	}

	sort.Slice(violations, func(i, j int) bool {
		if violations[i].Path != violations[j].Path {
			return violations[i].Path < violations[j].Path
		}
		if violations[i].Method != violations[j].Method {
			return violations[i].Method < violations[j].Method
		}
		return violations[i].Kind < violations[j].Kind
	})
	return violations, noteDrifts
}

// FormatViolations renders the CI failure message for the given violations.
func FormatViolations(violations []Violation) string {
	var b strings.Builder
	fmt.Fprintf(&b, "route-authority conformance failed: %d violation(s)\n", len(violations))
	for _, v := range violations {
		switch v.Kind {
		case "undeclared":
			fmt.Fprintf(&b, "  - %s %s: route exists but is undeclared (derived level %s)\n", v.Method, v.Path, v.Derived)
		case "vanished":
			fmt.Fprintf(&b, "  - %s %s: declared route no longer exists (was %s)\n", v.Method, v.Path, v.Declared)
		case "level-mismatch":
			fmt.Fprintf(&b, "  - %s %s: derived level %s != declared level %s\n", v.Method, v.Path, v.Derived, v.Declared)
		}
	}
	fmt.Fprintf(&b, "\nRemediation: this is expected only when the route table or middleware\n")
	fmt.Fprintf(&b, "chain changed intentionally. Regenerate the table and review the diff:\n")
	fmt.Fprintf(&b, "  go run ./cmd/route-authority-guard -update\n")
	return b.String()
}

func sortRoutes(routes []Route) {
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].Path != routes[j].Path {
			return routes[i].Path < routes[j].Path
		}
		return routes[i].Method < routes[j].Method
	})
}
